# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
trigger:
  branches:
    include:
    - v9.0
  batch: True
schedules:
- cron: 0 6 * * 1
  branches:
    include:
    - v9.0
  always: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: v9.0
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    name: DotNetCoreCLI_1
    displayName: Restore
    inputs:
      command: restore
      projects: '**/EssentialCSharp.sln'
  - task: DotNetCoreCLI@2
    name: DotNetCoreCLI_2
    displayName: Build
    inputs:
      projects: '**/EssentialCSharp.sln'
      arguments: --configuration $(BuildConfiguration) -p:LangVersion=9.0 -p:IgnoreExpectedWarnings=true -p:TreatWarningsAsErrors=true
  - task: DotNetCoreCLI@2
    name: DotNetCoreCLI_3
    displayName: Test
    inputs:
      command: test
      projects: $(System.DefaultWorkingDirectory)/EssentialCSharp.sln
      arguments: --configuration $(BuildConfiguration) -p:LangVersion=9.0 -p:NullableContextOptions=enable --collect:"XPlat Code Coverage"
  - task: reportgenerator@4
    displayName: ReportGenerator
    inputs:
      reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
      targetdir: $(System.DefaultWorkingDirectory)/CoverageReport
      verbosity: Verbose
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage from $(System.DefaultWorkingDirectory)/CoverageReport/Cobertura.xml
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/CoverageReport/Cobertura.xml
      failIfCoverageEmpty: true
  - task: DotNetCoreCLI@2
    name: DotNetCoreCLI_4
    displayName: Publish
    enabled: False
    inputs:
      command: publish
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    name: PublishBuildArtifacts_5
    displayName: Publish Artifact
    condition: succeededOrFailed()
    enabled: False
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
